version: "3"

services:
  db-nocountry:
    container_name: db-nocountry
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nocountry_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    expose:
      - 3308