name: Build and Deploy Market Place App

on:
  push:
    branches:
      - demo
jobs:
  build-deploy:
    name: Build and Deploy Market Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host-port: 3308
          container-port: 3306
          character-set-server: utf8mb4
          collation-server: utf8mb4_general_ci
          mysql-version: 8.0.33
          mysql-database: nocountry_db
          mysql-root-password: ${{ secrets.DB_ROOT_PASSWORD }}
          mysql-user: dev
          mysql-password: ${{ secrets.DB_PASSWORD }}

        env:
          MYSQL_DATABASE: nocountry_db
          MYSQL_USER: dev
          MYSQL_PASSWORD: 1234
          MYSQL_ROOT_PASSWORD: root

      - name: Unit Tests
        run: mvn -B test --file pom.xml
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/nocountry_db?serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: dev
          SPRING_DATASOURCE_PASSWORD: 1234

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/c16-85-ft-java:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/c16-85-ft-java:today