name: Build and Deploy Market Place App

on:
  push:
    branches:
      - demo
jobs:
  build-deploy:
    name: Build and Deploy Market Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml -e -X

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml