name: Build and Deploy Market Place App

on:
  push:
    branches:
      - demo
jobs:
  build-deploy:
    name: Build and Deploy Market Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK  17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version:  17

      - name: Run tests with Docker Compose
        run: |
          docker-compose up -d db-nocountry
          mvn -B test --file pom.xml
          docker-compose down

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/c16-85-ft-java:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/c16-85-ft-java:today